from __future__ import annotations

from collections.abc import Iterable
from typing import Callable

from fnutil.if_ import If
from fnutil.iterator import Iterator
from fnutil.match import MatchType, MatchValue

__all__ = [
    "expr",
    "Expr",
]

class Expr[T]:
    value: T
    err: bool

    def __init__(self, value: T, /, err: bool = False): ...
    def match_type[V](self) -> MatchType[T, V]: ...
    def match_value[V](self) -> MatchValue[T, V]: ...
    def if_[V](self, fn: Callable[[], V]) -> If[V]: ...
    def iterate[U](self: Expr[Iterable[U]]) -> Iterator[U]: ...
    def map_value[V](self, fn: Callable[[T], V]) -> Expr[V]: ...
    def try_map_value[V](self, fn: Callable[[T], V]) -> Expr[V | Exception]: ...
    def catch[E, V](self, exception: type[E], fn: Callable[[E], V]) -> Expr[T | V]: ...

def expr[T](value: T, /) -> Expr[T]: ...
