from __future__ import annotations

from typing import Callable

__all__ = [
    "MatchValue",
    "MatchType",
    "match_value",
    "match_type",
]

def match_value[T, V](value: T) -> MatchValue[T, V]: ...
def match_type[T, V](value: T) -> MatchType[T, V]: ...

class MatchValue[T, V]:
    def __init__(self, value: T, /): ...
    def case(
        self, value: T, fn_or_value: Callable[[T], V] | V, /
    ) -> MatchValue[T, V]: ...
    def default(self, fn_or_value: Callable[[T], V] | V, /) -> MatchValue[T, V]: ...
    def evaluate(self) -> V: ...

class MatchType[T, V]:
    def __init__(self, value: T): ...
    def case(
        self, annotation: type, fn_or_value: Callable[[T], V] | V, /
    ) -> MatchType[T, V]: ...
    def default(self, fn_or_value: Callable[[T], V] | V, /) -> MatchType[T, V]: ...
    def evaluate(self) -> V: ...
